### ISSUE TITLE
Split a Windows image file (.wim) to span across multiple files

### ISSUE THREAD

**Issue by lrs955** [KyodaiKen/DISMBackup#1]
Just a suggestion if its possible to add the possibility to split a Windows image file (.wim) to span across multiple files

**Comment by KyodaiKen** [comment]
It depends if DISM supports this. I will read the documentation and try to add an option for this in the script if possible.

**Comment by lrs955** [comment]
Hello!
https://learn.microsoft.com/en-us/windows-hardware/manufacture/desktop/split-a-windows-image--wim--file-to-span-across-multiple-dvds?view=windows-11 
i found this if if it can help.
Thank you for your tool!

**Comment by KyodaiKen** [comment]
> Hello! https://learn.microsoft.com/en-us/windows-hardware/manufacture/desktop/split-a-windows-image--wim--file-to-span-across-multiple-dvds?view=windows-11 i found this if if it can help. Thank you for your tool!

Looks like this is a second step, kind of like in FFMPEG when you want the MP4/MOV index at the beginning of the file, it remuxes the file after encoding video/audio as a second step. I hope `/Split-Image` and `/Filesize` can be combined with `/Capture-Image`. Because especially when using SSDs, it's causing unnecessary write cycles.

I will look into this after work.

**Comment by KyodaiKen** [comment]
I am also wondering how restoring those images will work. Do you plan to burn it onto DVDs or BDs like the M-Disks? I wonder if DISM has the "patience" to ask for the next disk... Hum...

**Comment by lrs955** [comment]
No, I'm not going to burn them to a disk, i preferred to split the wim file for an easier management. 
The link I indicated was just to show the fact that dism allows you to split files in some ways!

**Comment by KyodaiKen** [comment]
Unfortunately it looks like DISM does not support it to combine the size limit `/FileSize:4700` for splitting the image when using `/Capture-Image`. It can only be done as a second step after creating the WIM file, like described in the link you've sent.

I was planning to make a small piping program that can be put between DISM and writing the files but the issue here is that DISM does not support piping either. It wants direct file access to write a WIM file and does not allow piping the data output into another program.

So the only solution I can offer you is this little script to be run after the WIM has been created:

## split-wim.cmd

```batch
@echo off
set wim=%1
set swm=%2
set fs=%3
set dism=%systemroot%\system32\dism.exe
IF NOT EXIST %dism% (
  set dism=dism.exe
  IF NOT EXIST %dism% (
    ECHO Could not find DISM anywhere.
    EXIT /B 2
  )
)
IF NOT DEFINED wim (
  ECHO Please specify the source WIM file.
  EXIT /B 5
)

IF NOT DEFINED swm (
  ECHO Please specify the output filen ame.
  EXIT /B 6
)

%DISM% /Split-Image /ImageFile:%wim% /SWMFile:%swm% /FileSize:%fs%
```

Usage: `split-wim "E:\backups\feline\system\20231031184201.WIM" D:\temp\test.swm 1000`

Note: The process does not show any progress bar in the console.

If you want this solution to be integrated into `backup.cmd`, you can still comment here and I'll help you do that! 😸

**Comment by lrs955** [comment]
Thank you!!
